# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ../../Week12_code/5-b7/5-b7-cct.o ../../Week12_code/5-b7/5-b7-main.o
LINKOBJ  = ../../Week12_code/5-b7/5-b7-cct.o ../../Week12_code/5-b7/5-b7-main.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../Week12_code/5-b7/5-b7-cct.o: ../../Week12_code/5-b7/5-b7-cct.cpp
	$(CPP) -c ../../Week12_code/5-b7/5-b7-cct.cpp -o ../../Week12_code/5-b7/5-b7-cct.o $(CXXFLAGS)

../../Week12_code/5-b7/5-b7-main.o: ../../Week12_code/5-b7/5-b7-main.cpp
	$(CPP) -c ../../Week12_code/5-b7/5-b7-main.cpp -o ../../Week12_code/5-b7/5-b7-main.o $(CXXFLAGS)
